makes things easier

diff --git a/bin/dacti b/bin/dacti
--- a/bin/dacti
+++ b/bin/dacti
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-
+#
 # Copyright 2014 -- 2017 D630
 # https://github.com/D630/dacti
 
@@ -50,58 +50,57 @@ else
     command dmenu -p "${1:-$prompt}" 0<&-;
 fi;
 
-function Dacti::ExecApp () (
+function Dacti::ExecApp {
     if
         typeset -F Dacti::ExecAppCustom 1>/dev/null 2>&1;
     then
         Dacti::ExecAppCustom;
     else
+        (
         command -v "$command" 1>/dev/null 2>&1 ||
             return 1;
         IFS=' ';
-        case ${App[flags]} in
-            (nk)
-                exec $term -e "${SHELL:-sh}" -c "${command[*]};${SHELL:-sh}" &;;
-            (n)
+        case ${App[keep]}${App[nterminal]}${App[terminal]} in
+            (nt)
                 exec $term -e "${SHELL:-sh}" -c "${command[*]}" &;;
             (k)
-                if
-                    [[ ${App[mode]} == tui && $in_tty == \? ]];
-                then
-                    exec $term -e "${SHELL:-sh}" -c "${command[*]};command printf 'Press ENTER to continue\n';read" &
-                else
-                    exec ${SHELL:-sh} -c "${command[*]};command printf 'Press ENTER to continue\n';read";
-                fi;;
+                exec ${SHELL:-sh} -c "${command[*]};printf 'Press ENTER to continue\n';read";;
+            (knt)
+                exec $term -e "${SHELL:-sh}" -c "${command[*]};${SHELL:-sh}" &;;
+            (t)
+                case $in_tty in
+                    (\?)
+                        exec $term -e "${SHELL:-sh}" -c "${command[*]}" &;;
+                    (*)
+                        exec "${command[@]}";;
+                esac;;
+            (kt)
+                case $in_tty in
+                    (\?)
+                        exec $term -e "${SHELL:-sh}" -c "${command[*]};${SHELL:-sh}" &;;
+                    (*)
+                        exec ${SHELL:-sh} -c "${command[*]};printf 'Press ENTER to continue\n';read";;
+                esac;;
             ('')
                 case $in_tty in
                     (\?)
-                        if
-                            [[ ${App[mode]} == tui ]];
-                        then
-                            exec $term -e "${SHELL:-sh}" -c "${command[*]}" &
-                        else
-                            exec "${command[@]}" &
-                        fi;;
+                        exec "${command[@]}" &;;
                     (*)
                         exec "${command[@]}";;
                 esac;;
         esac;
+        )
     fi;
-);
+};
 
 function Dacti::Main {
     case $1 in
         (-h|--help)
             Dacti::PrintHelp;
             exit 0;;
-        (-v|--version)
-            Dacti::PrintVersion;
-            exit 0;;
     esac;
 
     typeset \
-        predir_confdir=${XDG_CONFIG_HOME:-$HOME/.config} \
-        predir_datadir=${XDG_DATA_HOME:-$HOME/.local/share} \
         prompt=\> \
         selection \
         term=xterm;
@@ -109,8 +108,8 @@ function Dacti::Main {
     typeset -i DACTI_PRETEND=$DACTI_PRETEND;
 
     typeset \
-        DACTI_CONF_FILE=${DACTI_CONF_FILE:-$predir_confdir/dacti/dactirc} \
-        DACTI_INDEX_FILE=${DACTI_INDEX_FILE:-$predir_datadir/dacti/dacti.index};
+        DACTI_CONF_FILE=${DACTI_CONF_FILE:-${XDG_CONFIG_HOME:-$HOME/.config}/dacti/dactirc} \
+        DACTI_INDEX_FILE=${DACTI_INDEX_FILE:-${XDG_DATA_HOME:-$HOME/.local/share}/dacti/dacti.index};
 
     typeset -a menu=(
         BIN-ASC
@@ -120,9 +119,7 @@ function Dacti::Main {
         INSERT
     ) apps;
 
-    typeset -r \
-        DACTI_CONF_FILE \
-        in_tty=$(command ps -p "$PPID" -o tty=);
+    typeset -r in_tty=$(command ps -p "$PPID" -o tty=);
 
     if
         [[ -e $DACTI_CONF_FILE ]];
@@ -138,24 +135,21 @@ function Dacti::Main {
     if
         [[ -e $DACTI_INDEX_FILE ]]
     then
-        function block { false; };
         function reg {
             DactiApps+=(
-                [app $3]=$3
+                [app $3]=${3:?}
                 [status $3]=reg
-                [mode $3]=${1%%:*}
-                [class $3]=$2
-                [flags $3]=${1##*:}
+                [class $3]=${2:?}
+                [flags $3]=${1:?}
             );
             apps+=("$3");
         };
         function ign {
             DactiApps+=(
-                [app $3]=$3
+                [app $3]=${3:?}
                 [status $3]=ign
-                [mode $3]=${1%%:*}
-                [class $3]=$2
-                [flags $3]=${1##*:}
+                [class $3]=${2:?}
+                [flags $3]=${1:?}
             );
             apps+=("$3");
         };
@@ -170,7 +164,7 @@ function Dacti::Main {
     do
         selection=$(
             Dacti::PrintMenu0 |
-            sort |
+            sort -u |
             Dacti::CmdMenu;
         );
         case ${selection,,} in
@@ -213,85 +207,89 @@ function Dacti::ParseSelection {
     [[ -n $* ]] ||
         return 1;
 
-    typeset \
-        pref_opts \
-        pref_status \
-        pref_mode;
+    typeset pref_class;
 
     typeset -i \
-        pref_idx= \
-        pref_keep= \
-        pref_nterminal= \
+        pref_idx=1 \
         pref_pretend=$DACTI_PRETEND \
-        s= ;
+        s=;
 
-    typeset -a command=($1);
+    typeset -a command=($@);
 
-    typeset -A App;
+    typeset -A App=(
+        [flags]=
+        [keep]=
+        [display]=
+        [nterminal]=
+        [terminal]=
+        [status]=reg
+    );
 
-    [[ $command == :* ]] && {
+    if
+        [[ $command == :* ]];
+    then
+        ((${#command[@]} > 1)) || {
+            printf 'Error: Command missing\n' 1>&2;
+            return 1;
+        };
         while
             read -r -n 1;
         do
             case $REPLY in
                 (k)
-                    pref_keep=1;;
-                (c)
-                    pref_mode=cli;;
+                    App[keep]=k;;
+                (d)
+                    App[display]=d;;
                 (i)
-                    pref_status=ign;;
+                    App[status]=ign;;
                 (n)
-                    pref_nterminal=1;;
+                    App[terminal]=t;
+                    App[nterminal]=n;;
                 (p)
                     pref_pretend=1;;
                 (t)
-                    pref_mode=tui;;
-                (u)
-                    pref_idx=1;;
+                    App[terminal]=t;;
             esac;
         done <<< "${command#:}";
-
         command=(${command[@]:1});
-    };
-
-    if
-        ((pref_pretend + pref_idx == 0));
-    then
+    else
         if
             [[ -v "DactiApps[app $command]" ]];
         then
+            pref_idx=0;
             while
                 read -r -n 1;
             do
                 case $REPLY in
                     (k)
-                        pref_keep=1;;
+                        App[keep]=k;;
                     (n)
-                        pref_nterminal=1;;
+                        App[nterminal]=n;;
+                    (d)
+                        App[display]=d;;
+                    (t)
+                        App[terminal]=t;;
                 esac;
             done <<< "${DactiApps[flags $command]}";
+            App[status]=${DactiApps[status $command]};
+            pref_class=${DactiApps[class $command]};
         fi;
-        [[ -n ${DactiApps[status $command]} ]] ||
-            pref_idx=1;
     fi;
 
-    ((pref_keep)) &&
-        pref_opts=k;
-    ((pref_nterminal)) &&
-        pref_opts+=n;
+    [[ -z $DISPLAY && -n ${App[display]} ]] && {
+        printf 'Error: App depends on DISPLAY\n' 1>&2;
+        return 1;
+    };
 
-    App[status]=${pref_status:-${DactiApps[status $command]}};
-    App[status]=${App[status]:-reg};
-    App[flags]=$pref_opts
-    App[mode]=${pref_mode:-${DactiApps[mode $command]}};
-    App[mode]=${App[mode]:-gui};
+    App[flags]=${App[display]}${App[keep]}${App[nterminal]}${App[terminal]};
+    App[flags]=${App[flags]:--};
 
     if
-        [[ -n ${DactiApps[class $command]} ]];
+        [[ -n $pref_class ]];
     then
-        App[class]=${DactiApps[class $command]};
+        App[class]=$pref_class;
     elif
-        [[ ${App[mode]} != gui ]];
+        [[ -z ${App[display]} ]];
     then
         App[class]=-;
     else
@@ -306,8 +304,6 @@ function Dacti::ParseSelection {
         pref_pretend;
 
     case ${App[status]} in
-        (block)
-            ! :;;
         (ign)
             Dacti::ExecApp;;
         (reg)
@@ -320,7 +316,7 @@ function Dacti::ParseSelection {
 
     [[ $pref_idx$pref_pretend$s -eq 100 ]] &&
         printf %s\\n \
-            "${App[status]} ${App[mode]}${App[flags]} ${App[class]} $command" \
+            "${App[status]} ${App[flags]} ${App[class]} $command" \
             >> "$DACTI_INDEX_FILE";
 
     return $s;
@@ -329,35 +325,33 @@ function Dacti::ParseSelection {
 function Dacti::PrintHelp {
     { typeset help=$(</dev/fd/0); } <<'HELP'
 Usage
-    dacti [ -h | --help | -v | --version ]
+    dacti [ -h | --help ]
 
 Main selection menu: entries
-    [BIN-ASC]                       Browse executables within PATH. Sort
+    BIN-ASC                         Browse executables within PATH. Sort
                                     them in ascending order by their names.
-    [BIN-DESC]                      "" Sort them in descending order by their
+    BIN-DESC                        "" Sort them in descending order by their
                                     names.
-    [BIN-ATIME-ASC]                 "" Sort them in ascending order by their
+    BIN-ATIME-ASC                   "" Sort them in ascending order by their
                                     access times.
-    [BIN-ATIME-DESC]                "" Sort them in descending order by their
+    BIN-ATIME-DESC                  "" Sort them in descending order by their
                                     access times.
-    [INSERT]                        Open a menu with an empty list and insert
+    INSERT                          Open a menu with an empty list and insert
                                     a command.
-    <COMMAND>                       Launch application (run or raise).
+    [:MODIFIERS ]COMMAND            Launch application (run or raise) from
+                                    DACTI_INDEX_FILE.
 
 Main selecton menu: modifiers
-    :c                              Declare mode 'cli'.
-    :i                              Declare status 'ign'.
-    :k                              Keep the process. Wait for a key press
+    i                               Declare status 'ign'.
+    k                               Keep the process. Wait for a key press
                                     or spawn a new shell instance.
-    :n                              Run COMMAND in a new terminal emulator
+    d                               COMMAND depends on DISPLAY.
+    n                               Run COMMAND in a new terminal emulator
                                     window.
-    :p                              Don't check, whether COMMAND is indexed.
-                                    Launch it directly and create NO record.
-                                    See also env variable DACTI_PRETEND.
-    :t                              Declare mode 'tui'.
-    :u                              Don't check, whether COMMAND is indexed.
-                                    Launch it directly and create a new
+    p                               Launch COMMAND directly and create NO
                                     record.
+                                    See also env variable DACTI_PRETEND.
+    t                               COMMAND needs a controlling tty.
 
 Environment variables
     DACTI_CONF_FILE                 See function Dacti::Main
@@ -373,24 +367,21 @@ Configuration
         apps                        All app names from DACTI_INDEX_FILE.
         command                     Selected/Typed command list without prefixed
                                     modifiers.
-        menu                        See entry section above. Default:
-                                    BIN-ASC
-                                    BIN-ATIME-ASC
-                                    BIN-ATIME-DESC
-                                    BIN-DESC
-                                    INSERT
+        menu                        See entry section above.
     associative array variables
         App                         Parsed preferences for COMMAND:
-                                    <status>
-                                    <mode>
-                                    <flags>
                                     <class>
+                                    <display>
+                                    <flags>
+                                    <keep>
+                                    <nterminal>
+                                    <status>
+                                    <terminal>
         DactiApps                   Mapped entries from DACTI_INDEX_FILE:
-                                    <status COMMAND>
-                                    <mode COMMAND>
-                                    <FLAGS COMMAND>
-                                    <class COMMAND>
                                     <app COMMAND>
+                                    <class COMMAND>
+                                    <flags COMMAND>
+                                    <status COMMAND>
     functions
         Dacti::CmdMenuCustom        See doc/examples/dactirc
         Dacti::CmdMenuEmptyCustom   ""
@@ -433,37 +424,35 @@ function Dacti::PrintMenuBinDesc {
     command sort -ru;
 };
 
-function Dacti::PrintVersion {
-    printf %s\\n 0.2.7;
-};
-
 function Dacti::RaiseApp
 if
     typeset -F Dacti::RaiseAppCustom 1>/dev/null 2>&1;
 then
     Dacti::RaiseAppCustom;
 else
+    [[ -n $DISPLAY ]] || {
+        Dacti::ExecAppCustom;
+        return $?;
+    };
     typeset \
         class \
-        id \
         pid \
         wm_pid \
+        xid \
         xlist;
-
     typeset -a \
         pid_list \
         xids;
-
     read -r _ _ _ _ xlist < <(command xprop -root _NET_CLIENT_LIST);
 
     if
-        [[ ${App[mode]} == gui ]];
+        [[ -n ${App[display]} ]];
     then
-        for id in ${xlist//,/}; do
-            read -r _ _ class < <(command xprop -id "$id" WM_CLASS);
+        for xid in ${xlist//,/}; do
+            read -r _ _ class < <(command xprop -id "$xid" WM_CLASS);
             class=${class//\"/};
             [[ ${class/, /.} =~ ${App[class]} ]] &&
-                xids+=($id);
+                xids+=($xid);
         done;
     else
         for pid in $(command pgrep -d ' ' "$command"); do
@@ -474,22 +463,21 @@ else
                 pid_list+=(${pid// /});
             done;
         done;
-        for id in ${xlist//,/}; do
-            read -r _ _ wm_pid < <(command xprop -id "$id" _NET_WM_PID);
+        for xid in ${xlist//,/}; do
+            read -r _ _ wm_pid < <(command xprop -id "$xid" _NET_WM_PID);
             for pid in "${pid_list[@]}"; do
                 [[ $wm_pid == $pid ]] &&
-                    xids+=($id);
+                    xids+=($xid);
             done;
         done;
     fi;
-
     case ${#xids[@]} in
         (0)
             Dacti::ExecApp;;
         (1)
             command wmctrl -i -a "$xids";;
         (*)
-            for id in "${xids[@]}"; do
+            for xid in "${xids[@]}"; do
                 command wmctrl -i -a "$id" ||
                     return $?;
             done;
