v0.1.0.6: revise fns __dacti_update{applications,categories,keywords}

diff --git a/dacti b/dacti
--- a/dacti
+++ b/dacti
@@ -34,7 +34,7 @@
 
 # -- FUNCTIONS.
 
-__dacti_version() { echo "0.1.0.5" ; }
+__dacti_version() { echo "0.1.0.6" ; }
 
 __dacti_help()
 {
@@ -656,97 +656,109 @@ __dacti_comm_array()
 
 __dacti_update_applications()
 {
-    declare \
-            file= \
-            mode= \
-            path=
+    builtin declare \
+        file= \
+        mode= \
+        path=
 
     exec 3>>"$DACTI_APPS_INDEX_FILE"
+
     if [[ -f $DACTI_APPS_CACHE_FILE ]]
     then
         # If there is an application cache file, then compare it with the current state and update the application index file.
-        while read -r _ file
+        while builtin read -r _ file
         do
             path=$file
             file=${file##*/}
-            mode=gui
-            sed -i -e "/^.* \<${file%.desktop}\> .*/ d" "$DACTI_APPS_INDEX_FILE"
-            egrep -q -e 'Terminal=(1|[tT]rue|[yY]es)' "$path" && mode=cli
-            printf '%s\n' "reg ${mode:-gui} ${file%.desktop} ${path}" 1>&3
-        done < <(comm -23 <(find ${xdg_applications[*]} $xdg_applications_home -name '*.desktop' -printf '%T@ %p\n' | sort -n | tee "${DACTI_APPS_CACHE_FILE}.$$") "$DACTI_APPS_CACHE_FILE")
-        mv -- "${DACTI_APPS_CACHE_FILE}.$$" "${DACTI_APPS_CACHE_FILE}"
+            command sed -i -e "/^.* \<${file%.desktop}\> .*/ d" "$DACTI_APPS_INDEX_FILE"
+            if command egrep -q -e 'Terminal=(1|[tT]rue|[yY]es)' "$path"
+            then
+                mode=cli
+            else
+                mode=gui
+            fi
+            builtin printf '%s\n' "reg ${mode} ${file%.desktop} ${path}" 1>&3
+        done < <(command comm -23 <(command find ${xdg_applications[*]} $xdg_applications_home -name '*.desktop' -printf '%T@ %p\n' 2>/dev/null | command sort -n | command tee "${DACTI_APPS_CACHE_FILE}.$$") "$DACTI_APPS_CACHE_FILE")
+        command mv -- "${DACTI_APPS_CACHE_FILE}.$$" "${DACTI_APPS_CACHE_FILE}"
     else
         # If there is no cache file, create a new index file.
-        while read -r _ file
+        while builtin read -r _ file
         do
             path=$file
             file=${file##*/}
-            mode=gui
-            egrep -q -e 'Terminal=(1|[tT]rue|[yY]es)' "$path" && mode=cli
-            printf '%s\n' "reg ${mode:-gui} ${file%.desktop} ${path}" 1>&3
-        done < <(find ${xdg_applications[*]} $xdg_applications_home -name '*.desktop' -printf '%T@ %p\n' | sort -n | tee "$DACTI_APPS_CACHE_FILE")
+            if command egrep -q -e 'Terminal=(1|[tT]rue|[yY]es)' "$path"
+            then
+                mode=cli
+            else
+                mode=gui
+            fi
+            builtin printf '%s\n' "reg ${mode} ${file%.desktop} ${path}" 1>&3
+        done < <(command find ${xdg_applications[*]} $xdg_applications_home -name '*.desktop' -printf '%T@ %p\n' 2>/dev/null | command sort -n | command tee "$DACTI_APPS_CACHE_FILE")
     fi
+
     exec 3<&-
+
+    __dacti_logger "Applications: Update has been proccessed"
 }
 
 __dacti_update_categories()
 {
-    declare \
-            cats= \
-            file= \
-            i=
+    builtin declare \
+        cats= \
+        file= \
+        i=
 
-    declare -a \
-               categories=() \
-               main=() \
-               sub=()
+    builtin declare -a \
+        "categories=()" \
+        "main=()" \
+        "sub=()"
 
-    cd -- "$DACTI_CATS_DATA_DIR" || return 1
+    builtin cd -- "$DACTI_CATS_DATA_DIR" || __dacti_status_code 1 "Categories: Could not cd into dir '${DACTI_CATS_DATA_DIR}'"
 
-    while IFS=':' read -r file cats
+    while IFS=':' builtin read -r file cats
     do
         cats=${cats#Categories=}
         categories=(${cats//;/ })
+        ((${#categories[@]} == 0)) && builtin continue
 
-        ((${#categories[@]} == 0)) && continue
-
-        mapfile -t main < <(find . -mindepth 1 -maxdepth 1 -type d -print | fgrep -e "$(printf '%s\n' ${categories[@]})")
-        mapfile -t sub < <(__dacti_comm_array "${categories[@]}" -- "${main[@]#./}")
+        builtin mapfile -t main < <(command fgrep -e "$(builtin printf '%s\n' "${categories[@]}")" "$DACTI_CATS_MAIN_INFO_FILE")
+        builtin mapfile -t sub < <(__dacti_comm_array "${categories[@]}" -- "${main[@]}")
 
         for i in "${sub[@]}"
         do
-            grep -q "^${i}\>" "$DACTI_CATS_SUB_INFO_FILE" || unset -v "sub[$i]"
+            command grep -q "^${i}\>" "$DACTI_CATS_SUB_INFO_FILE" || builtin unset -v "sub[$i]"
         done
 
         if ((${#sub[@]} > 0))
         then
-            while IFS= read -rd ''
+            while IFS= builtin read -rd ''
             do
-                ln -f -s "$file" "$REPLY"
-            done < <(find ${main[*]} -mindepth 1 -type d -print0 | grep -zZ -f <(printf '%s$\n' ${sub[@]}))
+                command ln -f -s "$file" "$REPLY"
+            done < <(command find ${main[*]} -mindepth 1 -type d -print0 | command grep -zZ -f <(builtin printf '/%s$\n' "${sub[@]}"))
         else
             for i in "${main[@]}"
             do
-                ln -f -s "$file" "$i"
+                command ln -f -s "$file" "$i"
             done
         fi
-    done < <(find ${xdg_applications[*]} $xdg_applications_home -name '*.desktop' -exec grep -HR '^Categories' /dev/null {} + | tee "$DACTI_CATS_INDEX_FILE")
+    done < <(command find ${xdg_applications[*]} $xdg_applications_home -name '*.desktop' -exec grep -HR '^Categories' 2>/dev/null {} + | command tee "$DACTI_CATS_INDEX_FILE")
+
+    command find "$DACTI_CATS_DATA_DIR" -type l -xtype l -delete
+
+    __dacti_logger "Categories: Update has been proccessed"
 }
 
 __dacti_update_keywords()
 {
-    declare \
-            file= \
-            keywords=
+    command find ${xdg_applications[*]} $xdg_applications_home -name '*.desktop' \
+            -exec grep -HR '^Keywords=' 2>/dev/null {} + | \
+        command sed -e 's/ $//' -e 's/$/\;/' -e 's/\;\;/\;/' -e 's/\; /\;/g' | \
+        command tee "$DACTI_KEYWS_INDEX_FILE" | \
+        command sed -e 's/^.*:Keywords=//' -e 's/;/\n/g' | \
+        command grep -v -e '^$' | \
+        command sort -u  > "$DACTI_KEYWS_CACHE_FILE"
 
-    while IFS=':' read -r file keywords
-    do
-        keywords=${keywords#Keywords=}
-        while read -r -d ';'
-        do
-            printf '%s\n' "$REPLY"
-        done <<< "$keywords"
-    done < <(find ${xdg_applications[*]} $xdg_applications_home -name '*.desktop' -exec grep -HR '^Keywords=' /dev/null {} + | sed -e '{s/ $//;s/$/;/;s/;;/;/;s/; /;/g}' | tee "$DACTI_KEYWS_INDEX_FILE") | sort | uniq 1> "$DACTI_KEYWS_CACHE_FILE"
+    __dacti_logger "Keywords: Update has been proccessed"
 }
 
 __dacti_set_args()
@@ -759,7 +771,7 @@ __dacti_set_args()
             builtin declare -g "$o"
         done
     else
-        { builtin printf '%s\n' "Option -${opt} requires an argument." 1>&2 ; builtin exit 1 ; }
+        { builtin printf '%s\n' "Option '-${opt}' requires an argument" 1>&2 ; builtin exit 1 ; }
     fi
 }
 
@@ -787,8 +799,7 @@ __dacti_logger()
     printf '%s\n' "$(date +%Y-%m-%d_%H:%M:%N) event ${log_message}" 1>> "$DACTI_LOG_FILE"
 }
 
-
-__dacti_main()
+__dacti_set_environment()
 {
     builtin declare \
         arg= \
@@ -817,8 +828,8 @@ __dacti_main()
         esac
     done
 
-    builtin declare \
-        opt= \
+    builtin declare opt=
+    builtin declare -g \
         pretend= \
         quit= \
         update_applications= \
@@ -830,7 +841,7 @@ __dacti_main()
     while builtin getopts :acC:hkpqv opt
     do
         case $opt in
-            C)  __dacti_set_args "DACTI_CONF_FILE=$OPTARG"    ;;
+            C)  __dacti_set_args "DACTI_CONF_FILE=$OPTARG"      ;;
             a)  update_applications=update_applications         ;;
             c)  update_categories=update_categories             ;;
             h)  __dacti_help ; builtin exit 0                   ;;
@@ -838,13 +849,12 @@ __dacti_main()
             p)  pretend=pretend                                 ;;
             q)  quit=quit                                       ;;
             v)  __dacti_version ; builtin exit 0                ;;
-            :)  builtin printf '%s\n' "Option '-${OPTARG}' requires an argument." 1>&2
+            :)  builtin printf '%s\n' "Option '-${OPTARG}' requires an argument" 1>&2
                 builtin exit 1                                  ;;
-            \?) builtin printf '%s\n' "Unknown flag: '-${OPTARG}'." 1>&2
+            \?) builtin printf '%s\n' "Unknown flag: '-${OPTARG}'" 1>&2
                 builtin exit 1
         esac
     done
-    builtin shift $((OPTIND-1))
 
     # Declare some enviroments, before we will source a conf file.
     builtin declare \
@@ -861,9 +871,9 @@ __dacti_main()
     if [[ -f $DACTI_CONF_FILE ]]
     then
         builtin source "$DACTI_CONF_FILE" 2>/dev/null || \
-        { builtin printf '%s\n' "${0##*/}:Status:Error:1: ${DACTI_CONF_FILE} has not been sourced." 1>&2 ; builtin exit 1 ; }
+        { builtin printf '%s\n' "${0##*/}:Status:Error:1: '${DACTI_CONF_FILE}' has not been sourced" 1>&2 ; builtin exit 1 ; }
     else
-         { builtin printf '%s\n' "${0##*/}:Status:Error:1: ${$DACTI_CONF_FILE} is not a regular file." 1>&2 ; builtin exit 1 ; }
+         { builtin printf '%s\n' "${0##*/}:Status:Error:1: '${$DACTI_CONF_FILE}' is not a regular file" 1>&2 ; builtin exit 1 ; }
     fi
 
     # Now declare all other enviroment variables.
@@ -883,13 +893,13 @@ __dacti_main()
     builtin declare -gr \
         DACTI_APPS_DIRS=${DACTI_APPS_DIRS:-${xdg_data_dirs}} \
         DACTI_APPS_DIR_HOME=${DACTI_APPS_DIR_HOME:-${predir_datadir}/applications}
-    builtin declare -gr xdg_applications_home=$DACTI_APPS_DIR_HOME
-    builtin declare -a "xdg_applications=(${DACTI_APPS_DIRS//:/ })"
-    builtin declare -gra "xdg_applications=(${xdg_applications[@]/%/\/applications})"
-    builtin declare -gr \
+    builtin declare -g xdg_applications_home=$DACTI_APPS_DIR_HOME
+    builtin declare -a xdg_applications='(${DACTI_APPS_DIRS//:/ })'
+    builtin declare -ga xdg_applications='(${xdg_applications[@]/%/\/applications})'
+    builtin declare -g \
         menu_0_prompt=${menu_0_prompt:->} \
         term=${term:-xterm}
-    builtin declare -gra "menu_0=(${menu_0[@]:-BIN-ASC BIN-ATIME-ASC BIN-ATIME-DESC BIN-DESC CATEGORIES KEYWORDS LOG OCCUR})"
+    builtin declare -ga menu_0='(${menu_0[@]:-BIN-ASC BIN-ATIME-ASC BIN-ATIME-DESC BIN-DESC CATEGORIES KEYWORDS LOG OCCUR})'
     builtin declare -g invocation_mode=
 
     # Check invocation mode.
@@ -900,8 +910,13 @@ __dacti_main()
     then
         invocation_mode=gui
     else
-        { builtin printf '%s\n' "${0##*/}:Status:Error:1: Neither cli nor gui mode." 1>&2 ; builtin exit 1 ; }
+        { builtin printf '%s\n' "${0##*/}:Status:Error:1: Neither cli nor gui mode" 1>&2 ; builtin exit 1 ; }
     fi
+}
+
+__dacti_main()
+{
+    __dacti_set_environment "$@"
 
     # Create index file and app dir, if they have not been created before.
     [[ -d $DACTI_DATA_DIR ]] || command mkdir -p "$DACTI_DATA_DIR"
@@ -911,21 +926,18 @@ __dacti_main()
     [[ $update_applications == update_applications ]] && __dacti_update_applications
     [[ $update_categories == update_categories ]] && __dacti_update_categories
     [[ $update_keywords == update_keywords ]] && __dacti_update_keywords
-    [[ $quit == quit ]] && __dacti_status_code 0 "Quit: With these command line options: ${index_applications:+${index_applications/%/ }}${update_categories:+${update_categories/%/ }}${update_keywords}."
+    [[ $quit == quit ]] && __dacti_status_code 0 "Quit: With these command line options: '$@'"
+    builtin shift $((OPTIND-1))
 
     # Unset variables and functions, we do not need anymore.
     builtin unset -v \
-        arg \
-        args \
-        delim \
-        opt \
-        predir_configdir
-        predir_datadir \
         quit \
         update_applications \
         update_categories \
         update_keywords
-    builtin unset -f __dacti_set_args
+    builtin unset -f \
+        __dacti_set_args \
+        __dacti_set_environment
 
     # Perform the main selection menu and handle selections.
     builtin declare -g selection=
@@ -966,7 +978,7 @@ __dacti_main()
                 __dacti_selection_custom "${selection//[\[\]]/}"
                 ;;
             "")
-                __dacti_status_code 0 "Quit: Nothing has been chosen."
+                __dacti_status_code 0 "Quit: Nothing has been chosen"
                 ;;
             *)
                 __dacti_check_status "$selection"
