reorder functions

diff --git a/dacti b/dacti
--- a/dacti
+++ b/dacti
@@ -27,61 +27,14 @@
 
 # -- FUNCTIONS.
 
-function Dacti::Init
-{
-        {
-                builtin typeset i="$(</dev/fd/0)"
-        } <<-'INIT'
-builtin typeset \
-        invocation_mode \
-        predir_datadir=${XDG_DATA_HOME:-${HOME}/.local.share} \
-        predir_confdir=${XDG_CONFIG_HOME:-${HOME}/.config} \
-        prompt=\> \
-        selection \
-        term=xterm ;
-
-builtin typeset -i DACTI_PRETEND=$DACTI_PRETEND
-
-builtin typeset \
-        DACTI_CONF_FILE=${DACTI_CONF_FILE:-${predir_confdir}/dacti/dactirc} \
-        DACTI_INDEX_FILE=${DACTI_INDEX_FILE:-${predir_datadir}/dacti/dacti.index}
-
-builtin typeset -a "menu=(
-        BIN-ASC
-        BIN-ATIME-ASC
-        BIN-ATIME-DESC
-        BIN-DESC
-)"
-
+function Dacti::CmdMenu
 if
-        command tty -s
+        builtin typeset -f Dacti::CmdMenuCustom 1>/dev/null 2>&1
 then
-        invocation_mode=cli
-elif
-        [[ -n $DISPLAY ]]
-then
-        invocation_mode=gui
+        Dacti::CmdMenuCustom "${1:-$prompt}"
 else
-        builtin printf '%s\n' "Error: Could not determine invocation mode" 1>&2
-        builtin return 1
+        command dmenu -p "${1:-$prompt}"
 fi
-
-builtin typeset -r \
-        DACTI_CONF_FILE \
-        invocation_mode ;
-
-[[ -f $DACTI_CONF_FILE ]] || {
-        command mkdir -p "${DACTI_CONF_FILE#*/}"
-}
-
-[[ -f $DACTI_INDEX_FILE ]] || {
-        command mkdir -p "${DACTI_INDEX_FILE#*/}"
-        > "$DACTI_INDEX_FILE"
-}
-INIT
-        builtin printf '%s' "$i"
-
-} 2>/dev/null
 
 function Dacti::ExecApp
 if
@@ -146,17 +99,6 @@ else
         launch_status=fail
 fi
 
-function Dacti::Main
-{
-        Dacti::GetArgs "$@" || {
-                builtin source <(Dacti::Init)
-                [[ -f "$DACTI_CONF_FILE" ]] && {
-                        builtin source "$DACTI_CONF_FILE"
-                }
-                Dacti::MainLoop
-        }
-}
-
 function Dacti::GetArgs
 case $1 in
 -h | --help)
@@ -169,65 +111,77 @@ case $1 in
         builtin return 1
 esac
 
-function Dacti::PrintVersion
+function Dacti::IndexApp
 {
-        builtin printf 'v%s\n' "0.2"
+        >> "$DACTI_INDEX_FILE" \
+        builtin printf '%s\n' "${App[status]} ${App[mode]}${opts:+:${opts}} ${App[class]} ${command[0]}"
 }
 
-function Dacti::PrintHelp
+function Dacti::Init
 {
         {
-                builtin typeset help="$(</dev/fd/0)"
-        } <<'HELP'
-Usage
-        dacti [ -h | --help | -v | --version ]
+                builtin typeset i="$(</dev/fd/0)"
+        } <<-'INIT'
+builtin typeset \
+        invocation_mode \
+        predir_datadir=${XDG_DATA_HOME:-${HOME}/.local.share} \
+        predir_confdir=${XDG_CONFIG_HOME:-${HOME}/.config} \
+        prompt=\> \
+        selection \
+        term=xterm ;
 
-Main selection menu: entries
-        [BIN-ASC]                       Browse executables within <PATH>. Sort
-                                        them in ascending order by their names
-        [BIN-DESC]                      "" Sort them in descending order by their
-                                        names
-        [BIN-ATIME-ASC]                 "" Sort them in ascending order by their
-                                        access times
-        [BIN-ATIME-DESC]                "" Sort them in descending order by their
-                                        access times
-        <COMMAND>                       Launch application (run or raise)
+builtin typeset -i DACTI_PRETEND=$DACTI_PRETEND
 
-Main selecton menu: command prefixes
-        :b                              Execute COMMAND in background
-        :c                              Declare mode 'cli'
-        :i                              Declare status 'ign'
-        :k                              Keep the process. Wait for a key press
-                                        or spawn a new shell instance
-        :l                              Declare status 'block'
-        :n                              Run COMMAND in a new terminal emulator
-                                        window
-        :p                              Don't check, wheater COMMAND is indexed.
-                                        Launch it directly and create NO record.
-                                        See env DACTI_PRETEND
-        :t                              Declare mode 'tui'
-        :u                              Don't check, wheater COMMAND is indexed.
-                                        Launch it directly and create a new
-                                        record.
+builtin typeset \
+        DACTI_CONF_FILE=${DACTI_CONF_FILE:-${predir_confdir}/dacti/dactirc} \
+        DACTI_INDEX_FILE=${DACTI_INDEX_FILE:-${predir_datadir}/dacti/dacti.index}
 
-Environment variables
-        DACTI_CONF_FILE                 See function Dacti::Init
-        DACTI_INDEX_FILE                ""
-        DACTI_PRETEND                   Default: 0
+builtin typeset -a "menu=(
+        BIN-ASC
+        BIN-ATIME-ASC
+        BIN-ATIME-DESC
+        BIN-DESC
+)"
 
-Configuration
-        normal scalar variables
-            prompt                      Default: >
-            term                        Default: xterm
-        indexed array variables
-            menu                        See entry section above
-        functions
-            Dacti::CmdMenuCustom        See doc/examples/dactirc
-            Dacti::ParseSelectionCustom ""
-            Dacti::RaiseAppPlCustom     ""
-            Dacti::RaiseAppSgCustom     ""
-HELP
-        builtin printf '%s\n' "$help"
+if
+        command tty -s
+then
+        invocation_mode=cli
+elif
+        [[ -n $DISPLAY ]]
+then
+        invocation_mode=gui
+else
+        builtin printf '%s\n' "Error: Could not determine invocation mode" 1>&2
+        builtin return 1
+fi
+
+builtin typeset -r \
+        DACTI_CONF_FILE \
+        invocation_mode ;
+
+[[ -f $DACTI_CONF_FILE ]] || {
+        command mkdir -p "${DACTI_CONF_FILE#*/}"
+}
+
+[[ -f $DACTI_INDEX_FILE ]] || {
+        command mkdir -p "${DACTI_INDEX_FILE#*/}"
+        > "$DACTI_INDEX_FILE"
+}
+INIT
+        builtin printf '%s' "$i"
+
+} 2>/dev/null
+
+function Dacti::Main
+{
+        Dacti::GetArgs "$@" || {
+                builtin source <(Dacti::Init)
+                [[ -f "$DACTI_CONF_FILE" ]] && {
+                        builtin source "$DACTI_CONF_FILE"
+                }
+                Dacti::MainLoop
+        }
 }
 
 function Dacti::MainLoop
@@ -276,12 +230,6 @@ do
                 Dacti::ParseSelection "$selection"
         esac
 done
-
-function Dacti::IndexApp
-{
-        >> "$DACTI_INDEX_FILE" \
-        builtin printf '%s\n' "${App[status]} ${App[mode]}${opts:+:${opts}} ${App[class]} ${command[0]}"
-}
 
 function Dacti::ParseSelection
 {
@@ -430,6 +378,62 @@ function Dacti::ParseSelection
         builtin return 1
 }
 
+function Dacti::PrintHelp
+{
+        {
+                builtin typeset help="$(</dev/fd/0)"
+        } <<'HELP'
+Usage
+        dacti [ -h | --help | -v | --version ]
+
+Main selection menu: entries
+        [BIN-ASC]                       Browse executables within <PATH>. Sort
+                                        them in ascending order by their names
+        [BIN-DESC]                      "" Sort them in descending order by their
+                                        names
+        [BIN-ATIME-ASC]                 "" Sort them in ascending order by their
+                                        access times
+        [BIN-ATIME-DESC]                "" Sort them in descending order by their
+                                        access times
+        <COMMAND>                       Launch application (run or raise)
+
+Main selecton menu: command prefixes
+        :b                              Execute COMMAND in background
+        :c                              Declare mode 'cli'
+        :i                              Declare status 'ign'
+        :k                              Keep the process. Wait for a key press
+                                        or spawn a new shell instance
+        :l                              Declare status 'block'
+        :n                              Run COMMAND in a new terminal emulator
+                                        window
+        :p                              Don't check, wheater COMMAND is indexed.
+                                        Launch it directly and create NO record.
+                                        See env DACTI_PRETEND
+        :t                              Declare mode 'tui'
+        :u                              Don't check, wheater COMMAND is indexed.
+                                        Launch it directly and create a new
+                                        record.
+
+Environment variables
+        DACTI_CONF_FILE                 See function Dacti::Init
+        DACTI_INDEX_FILE                ""
+        DACTI_PRETEND                   Default: 0
+
+Configuration
+        normal scalar variables
+            prompt                      Default: >
+            term                        Default: xterm
+        indexed array variables
+            menu                        See entry section above
+        functions
+            Dacti::CmdMenuCustom        See doc/examples/dactirc
+            Dacti::ParseSelectionCustom ""
+            Dacti::RaiseAppPlCustom     ""
+            Dacti::RaiseAppSgCustom     ""
+HELP
+        builtin printf '%s\n' "$help"
+}
+
 function Dacti::PrintMenu0
 {
         builtin typeset \
@@ -480,14 +484,10 @@ function Dacti::PrintMenuBinDesc
         | command sort -ru
 }
 
-function Dacti::CmdMenu
-if
-        builtin typeset -f Dacti::CmdMenuCustom 1>/dev/null 2>&1
-then
-        Dacti::CmdMenuCustom "${1:-$prompt}"
-else
-        command dmenu -p "${1:-$prompt}"
-fi
+function Dacti::PrintVersion
+{
+        builtin printf 'v%s\n' "0.2"
+}
 
 function Dacti::RaiseApp
 {
@@ -563,14 +563,6 @@ function Dacti::RaiseApp
         esac
 }
 
-function Dacti::RaiseAppSg
-{
-        command wmctrl -i -a "$1" || {
-                launch_status=fail
-                builtin return 1
-        }
-}
-
 function Dacti::RaiseAppPl
 {
         builtin typeset id
@@ -582,6 +574,14 @@ function Dacti::RaiseAppPl
                         builtin return 1
                 }
         done
+}
+
+function Dacti::RaiseAppSg
+{
+        command wmctrl -i -a "$1" || {
+                launch_status=fail
+                builtin return 1
+        }
 }
 
 # -- MAIN.
